### ISSUE TITLE
Default nodes

### ISSUE THREAD

**Issue by iahmad-khan** [dkalintsev/vTM-K8s-ServiceDiscovery#2]
Hi,

In Getting the nodes section of the script:

Since the kubernetes service nodeport can be access on any cluster node , can we just populate the pool with all the cluster nodes instead of the node on which the service is running?

**Comment by dkalintsev** [comment]
Hello,

This would beat the original intent of this plugin, which was to avoid bouncing traffic between nodes. This is needed if you are using things like session persistence.

The associated blog post (https://telecomoccasionally.wordpress.com/2018/05/17/use-pulse-virtual-traffic-manager-to-route-traffic-to-kubernetes-pods/) talks about this in point 3 of the Summary.

Hope this helps.
